name: HTML Validator

on:
  push:
    branches: html-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action-experimental@main
        with:
          root: ./public
          log_level: INFO
          css: true
